myrobot: #namespace
    ros_ws_abspath: "/home/dongyanqi/catkin_ws"
    model_name: "turtlebot3_burger"
    task_ros_package: "simulator_gazebo"
    task_launch_file: "TD3_UGV_task.launch"
    task_world_file: "indoor_region_map_mod_1.world"

    start_point_x: 1.5
    start_point_y: 1.5
    start_yaw: 3.14

    max_linear_speed: 0.22
    max_angular_speed: 2.0 # Angular speed when turning Left or Right
    
    scan_ob_dim: 40 # How many laser readings we jump in each observation reading, the bigger the less laser resolution
    max_goal_distance: 10

    goal_range: 0.2 # Minimum meters below wich we consider we have reached the target point
    min_range: 0.13 # Minimum meters below wich we consider we have crashed
    safe_distance: 0.4
    max_laser_value: 3 # Value considered Ok, no wall
    min_laser_value: 0 # Value considered there is an obstacle or crashed

    robot_radius: 0.1
    goal_point_x: -1.5
    goal_point_y: -1
    
    reward_scale_factor: 0.2
    reward_baseline: 3
    reach_target_reward: 200
    crash_penalty: -150
    forwards_reward: 1 # Points Given to go forwards
    backwards_reward: -3
    straight_reward: 3
    turn_reward: 1 # Points Given to turn as action
    end_episode_points: 200 # Points given when ending an episode
    

